spring:
  application:
    name: dayone-financial

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      useNewIdGeneratorMappings: false
    showSql: true
    defer-datasource-initialization: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: